spring:
  data:
    mongodb:
      database: CRM
      port: '27017'
      uri: mongodb+srv://root:mongodb@crm.5fnyhlo.mongodb.net/?retryWrites=true&w=majority&appName=CRM
  application:
    name: products2
  cloud:
    config:
      enabled: 'false'
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: '8081'
  